services:
  - type: web
    name: chatbot-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    rootDir: backend  # backend 

  - type: web
    name: chatbot-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://chatbot-backend.onrender.com"
    rootDir: frontend  # frontend folder
